FROM mcr.microsoft.com/playwright:v1.55.1-noble@sha256:2f29369043d81d6d69a815ceb80760f55e85f5020371ad06a4d996f18503ad1c

WORKDIR /workspace
COPY package.json package-lock.json ./
RUN npm ci

COPY index.html ./
COPY assets ./assets
COPY data ./data
COPY js ./js
COPY scripts ./scripts
COPY tests ./tests

CMD ["npm", "test"]
